# Generated by Django 5.2.5 on 2026-01-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_ip_address_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(blank=True, choices=[('password_reset', 'Password Reset'), ('login', 'Login'), ('delete_account', 'Delete Account'), ('account_create', 'Account Create')], max_length=50, null=True),
        ),
    ]
