# Generated by Django 5.2.4 on 2025-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_cover_photos/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profile_images/'),
        ),
    ]
