# Generated by Django 5.2.4 on 2025-08-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vendorprofile_shop_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
