# Generated by Django 5.2.4 on 2025-08-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0002_alter_aboutsystem_favicon_alter_aboutsystem_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hex_code', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
