# Generated by Django 5.2.4 on 2025-08-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0003_systemcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemcolor',
            old_name='hex_code',
            new_name='code',
        ),
    ]
